### ISSUE TITLE
Format of octopart.h

### ISSUE THREAD

**Issue by Gasman2014** [pioupus/kicadLibCreator#18]
I have an API key from Octopart. Building this in QTCreator fails with a 
```
/Users/#########/Kicad/kicadLibCreator/project/src/octopartinterface.cpp:11: error: '../octopartkey.h' file not found
#include "../octopartkey.h"
         ^
```

What format should the octopart.h file take? Just the API alone?

**Comment by pioupus** [comment]
please pull again. You can enter the api key via gui
