### ISSUE TITLE
Datasheet show button

### ISSUE THREAD

**Issue by pioupus** [pioupus/kicadLibCreator#34]
In fact it had worked before but i hadn't noticed the new directory pop up in my datasheet folder. However, when you click on 'Show' I would expect to either open the data sheet or at least shown it in the directory explorer - neither of which happens.

**Comment by pioupus** [comment]
can we find out if default application for datasheet is installed?

**Comment by Gasman2014** [comment]
Yes - 'Preview' is the default OS X .pdf viewer. It is installed and opens .pdf files normally. 

John Pateman

**Comment by pioupus** [comment]
does it work better now? if it cant open the file with the default app there will be a message.

**Comment by Gasman2014** [comment]
Yes, opens fine now - thank you.
