### ISSUE TITLE
Compile issues -fext-numeric-literals

### ISSUE THREAD

**Issue by Gasman2014** [pioupus/kicadLibCreator#47]
Hi,
I have updated to the latest version but I am now getting the following errors from QT Creator. Previous version was OK and compiled without issue. I am on macOS.

```
:-1: error: unknown argument: '-fext-numeric-literals'
:-1: error: [main.o] Error 1
```
Any advice?

**Comment by pioupus** [comment]
Did you already fix this? Because I dont have that issue.

**Comment by Gasman2014** [comment]
Yes, now seems to run OK following an QT Studio update and a few other tweaks - not sure what did it but seems OK now.
