### ISSUE TITLE
setCurrentText() in QComboBox is deprecated

### ISSUE THREAD

**Issue by Daniellandry62** [pioupus/kicadLibCreator#49]
kicadLibCreator seems a good application, but I can't compile it to make a try. I'm currently on Linux Mint 18.3, using Qt 5.5.1. According to my understanding, the following steps should be enough:

$ qmake
$ make

but I have the following error :

querymemory.cpp:52:10: error: ‘class QComboBox’ has no member named ‘setCurrentText’

According to http://www.qtcentre.org/printthread.php?t=8515&pp=20&page=1, setCurrentText is deprecated.

Maybe, I'm doing something wrong and some help is welcome. However, I wish I did not have to use a ppa to load a different version of Qt.

Is there a workaround for this issue? If I'm right, are you planning to update the software soon?

Best regards.
Daniel

**Comment by pioupus** [comment]
thank you for reporting that issue!
hope it works now

**Comment by Daniellandry62** [comment]
Thank you for having corrected the issue so quickly.

$ qmake
$ make clean
$ make

compilation is done without error. I have change BUILD_FOLDER=project in start_kicadlibcreator.sh and everything works fine.

I am a new user of kicad and I found that the BOM did not have enough information using the default kicad libraries. kicadLibCreator is a nice application to create our own libraries. I think this application will be very useful to me. Thank you very much.
